apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "sw.kogito.kie.org/v1alpha08",
          "kind": "KogitoServerlessPlatform",
          "metadata": {
            "name": "kogito-workflow-platform"
          },
          "spec": {
            "cluster": "kubernetes",
            "platform": {
              "registry": {
                "address": "quay.io/kiegroup",
                "secret": "regcred"
              }
            }
          }
        },
        {
          "apiVersion": "sw.kogito.kie.org/v1alpha08",
          "kind": "KogitoServerlessWorkflow",
          "metadata": {
            "annotations": {
              "sw.kogito.kie.org/description": "Greeting example on k8s!",
              "sw.kogito.kie.org/version": "0.0.1"
            },
            "name": "greeting"
          },
          "spec": {
            "functions": [
              {
                "name": "greetFunction",
                "operation": "sysout",
                "type": "custom"
              }
            ],
            "start": "ChooseOnLanguage",
            "states": [
              {
                "dataConditions": [
                  {
                    "condition": "${ .language == \"English\" }",
                    "transition": "GreetInEnglish"
                  },
                  {
                    "condition": "${ .language == \"Spanish\" }",
                    "transition": "GreetInSpanish"
                  }
                ],
                "defaultCondition": "GreetInEnglish",
                "name": "ChooseOnLanguage",
                "type": "switch"
              },
              {
                "data": {
                  "greeting": "Hello from JSON Workflow, "
                },
                "name": "GreetInEnglish",
                "transition": "GreetPerson",
                "type": "inject"
              },
              {
                "data": {
                  "greeting": "Saludos desde JSON Workflow, "
                },
                "name": "GreetInSpanish",
                "transition": "GreetPerson",
                "type": "inject"
              },
              {
                "actions": [
                  {
                    "functionRef": {
                      "arguments": {
                        "message": ".greeting+.name"
                      },
                      "refName": "greetFunction"
                    },
                    "name": "greetAction"
                  }
                ],
                "end": true,
                "name": "GreetPerson",
                "type": "operation"
              }
            ]
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.25.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: kogito-serverless-operator.v2.0.0-snapshot
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KogitoServerlessBuild is the Schema for the kogitoserverlessbuilds
        API
      displayName: Kogito Serverless Build
      kind: KogitoServerlessBuild
      name: kogitoserverlessbuilds.sw.kogito.kie.org
      version: v1alpha08
    - description: KogitoServerlessPlatform is the Schema for the kogitoserverlessplatforms
        API
      displayName: Kogito Serverless Platform
      kind: KogitoServerlessPlatform
      name: kogitoserverlessplatforms.sw.kogito.kie.org
      version: v1alpha08
    - description: KogitoServerlessWorkflow is the Schema for the kogitoserverlessworkflows
        API
      displayName: Kogito Serverless Workflow
      kind: KogitoServerlessWorkflow
      name: kogitoserverlessworkflows.sw.kogito.kie.org
      version: v1alpha08
  description: Kogito Serverless Workflow Operator
  displayName: kogito-serverlessworkflow-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - pods
          - pods/exec
          - services
          - services/finalizers
          - namespaces
          - serviceaccounts
          - persistentvolumeclaims
          - secrets
          - events
          - deployments
          - nodes
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - configmaps
          - pods
          - pods/exec
          - services
          - services/finalizers
          - namespaces
          - serviceaccounts
          - persistentvolumeclaims
          - secrets
          - events
          - deployments
          - nodes
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          - rolebindings
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - sw.kogito.kie.org
          resources:
          - kogitoserverlessbuilds
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - sw.kogito.kie.org
          resources:
          - kogitoserverlessbuilds/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - sw.kogito.kie.org
          resources:
          - kogitoserverlessplatforms
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - sw.kogito.kie.org
          resources:
          - kogitoserverlessplatforms/finalizers
          verbs:
          - update
        - apiGroups:
          - sw.kogito.kie.org
          resources:
          - kogitoserverlessplatforms/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - sw.kogito.kie.org
          resources:
          - kogitoserverlessworkflows
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - sw.kogito.kie.org
          resources:
          - kogitoserverlessworkflows/finalizers
          verbs:
          - update
        - apiGroups:
          - sw.kogito.kie.org
          resources:
          - kogitoserverlessworkflows/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - sw.kogito.kie.org
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: kogito-serverless-operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: kogito-serverless-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  seccompProfile:
                    type: RuntimeDefault
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/kiegroup/kogito-serverless-operator-nightly:2.0.0-snapshot
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: kogito-serverless-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: kogito-serverless-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kogito
  - serverless
  - serverlessworkflow
  links:
  - name: Kogito Serverless Operator
    url: https://kogito-serverless-operator.domain
  maturity: alpha
  provider:
    name: kogito-serverlessworkflow-operator
  version: 2.0.0-snapshot
