---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: builder-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - pods/exec
  - services
  - services/finalizers
  - namespaces
  - serviceaccounts
  - persistentvolumeclaims
  - secrets
  - events
  - deployments
  - nodes
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - apps
  resources:
    - configmaps
    - pods
    - pods/exec
    - services
    - services/finalizers
    - namespaces
    - serviceaccounts
    - persistentvolumeclaims
    - secrets
    - events
    - deployments
    - nodes
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - roles
    - rolebindings
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch