# permissions for end users to edit kogitoserverlessplatforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitoserverlessplatform-editor-role
rules:
- apiGroups:
  - sw.kogito.kie.org
  resources:
  - kogitoserverlessplatforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sw.kogito.kie.org
  resources:
  - kogitoserverlessplatforms/status
  verbs:
  - get
