# permissions for end users to view kogitoserverlessplatforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogitoserverlessplatform-viewer-role
rules:
- apiGroups:
  - sw.kogito.kie.org
  resources:
  - kogitoserverlessplatforms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sw.kogito.kie.org
  resources:
  - kogitoserverlessplatforms/status
  verbs:
  - get
