---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - sw.kogito.kie.org
  resources:
  - kogitoserverlessbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sw.kogito.kie.org
  resources:
  - kogitoserverlessbuilds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sw.kogito.kie.org
  resources:
  - kogitoserverlessplatforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sw.kogito.kie.org
  resources:
  - kogitoserverlessplatforms/finalizers
  verbs:
  - update
- apiGroups:
  - sw.kogito.kie.org
  resources:
  - kogitoserverlessplatforms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sw.kogito.kie.org
  resources:
  - kogitoserverlessworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sw.kogito.kie.org
  resources:
  - kogitoserverlessworkflows/finalizers
  verbs:
  - update
- apiGroups:
  - sw.kogito.kie.org
  resources:
  - kogitoserverlessworkflows/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sw.kogito.kie.org
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
