# permissions for end users to view sonataflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sonataflowworkflow-viewer-role
rules:
- apiGroups:
  - sonataflow.org
  resources:
  - sonataflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sonataflow.org
  resources:
  - sonataflows/status
  verbs:
  - get
