# permissions for end users to edit sonataflow.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sonataflowworkflow-editor-role
rules:
  - apiGroups:
      - sonataflow.org
    resources:
      - sonataflows
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sonataflow.org
    resources:
      - sonataflows/status
    verbs:
      - get
