apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kogito-serverless-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KogitoServerlessWorkflow is the Schema for the kogitoserverlessworkflows
        API
      displayName: Kogito Serverless Workflow
      kind: KogitoServerlessWorkflow
      name: kogitoserverlessworkflows.sw.kogito.kie.org
      version: v08
  description: Kogito Serverless Workflow Operator
  displayName: kogito-serverlessworkflow-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kogito
  - serverless
  - serverlessworkflow
  links:
  - name: Kogito Serverless Operator
    url: https://kogito-serverless-operator.domain
  maturity: alpha
  provider:
    name: kogito-serverlessworkflow-operator
  version: 0.0.0
