resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
- files:
  - Dockerfile=SonataFlow-Builder.containerfile
  literals:
  - DEFAULT_WORKFLOW_EXTENSION=.sw.json
  name: builder-config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:24c2e62bff1f2f7e5579b990e44206ac019bd00f5ca546b069471fc1af34ed75
  name: controller
  newName: registry.redhat.io/openshift-serverless-1-tech-preview/logic-operator-rhel8
# Patching the manager deployment file to add an env var with the operator namespace in
patchesJson6902:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    namespace: system
    version: v1
