apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  build:
    config:
      buildAttemptsAfterError: 3
      registry:
        address: quay.io/kiegroup
        secret: regcred
