apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  platform:
    buildAttemptsAfterError: 3
    registry:
      address: quay.io/kiegroup
      secret: regcred
