apiVersion: sw.kogito.kie.org/v1alpha08
kind: KogitoServerlessPlatform
metadata:
  name: kogito-workflow-platform
spec:
  cluster: kubernetes
  platform:
    publishStrategy: "Kaniko"
    baseImage: quay.io/kiegroup/kogito-swf-builder-nightly:latest
    PublishStrategyOptions:
      KanikoBuildCacheEnabled: "true"
