apiVersion: sw.kogito.kie.org/v1alpha08
kind: KogitoServerlessWorkflow
metadata:
  name: greeting
  annotations:
    sw.kogito.kie.org/description: Greeting example on k8s with Italian!
    sw.kogito.kie.org/version: 0.0.2
spec:
  start: ChooseOnLanguage
  functions:
    - name: greetFunction
      type: custom
      operation: sysout
  states:
    - name: ChooseOnLanguage
      type: switch
      dataConditions:
        - condition: "${ .language == \"English\" }"
          transition: GreetInEnglish
        - condition: "${ .language == \"Spanish\" }"
          transition: GreetInSpanish
        - condition: "${ .language == \"Italian\" }"
          transition: GreetInItalian
      defaultCondition: GreetInEnglish
    - name: GreetInEnglish
      type: inject
      data:
        greeting: "Hello from JSON Workflow, "
      transition: GreetPerson
    - name: GreetInSpanish
      type: inject
      data:
        greeting: "Saludos desde JSON Workflow, "
      transition: GreetPerson
    - name: GreetInItalian
      type: inject
      data:
        greeting: "Saluti dal JSON Workflow, "
      transition: GreetPerson
    - name: GreetPerson
      type: operation
      actions:
        - name: greetAction
          functionRef:
            refName: greetFunction
            arguments:
              message: ".greeting+.name"
      end: true
