apiVersion: sw.kogito.kie.org/v1alpha08
kind: KogitoServerlessPlatform
metadata:
  name: kogito-workflow-platform
spec:
  build:
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"
    arguments:
      - "--use-new-run=true"
      - "--cache=true"
      - "--cache-dir=/kaniko/cache"
  platform:
    registry:
      address: quay.io/kiegroup
      secret: regcred
    buildStrategyOptions:
      KanikoBuildCacheEnabled: "true"

