apiVersion: sw.kogito.kie.org/v1alpha08
kind: KogitoServerlessPlatform
metadata:
  name: kogito-workflow-platform
spec:
  cluster: kubernetes
  platform:
    publishStrategy: "Kaniko"
    registry:
      address: quay.io/kiegroup
      secret: regcred
    PublishStrategyOptions:
      KanikoBuildCacheEnabled: "true"

