//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2023 Red Hat, Inc. and/or its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha08

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"

	workflowproj "github.com/apache/incubator-kie-kogito-serverless-operator/workflowproj-apiserver/pkg/apis/workflowproj"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ProjObjectsRef)(nil), (*workflowproj.ProjObjectsRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha08_ProjObjectsRef_To_workflowproj_ProjObjectsRef(a.(*ProjObjectsRef), b.(*workflowproj.ProjObjectsRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*workflowproj.ProjObjectsRef)(nil), (*ProjObjectsRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_workflowproj_ProjObjectsRef_To_v1alpha08_ProjObjectsRef(a.(*workflowproj.ProjObjectsRef), b.(*ProjObjectsRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SonataFlowProjInstance)(nil), (*workflowproj.SonataFlowProjInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha08_SonataFlowProjInstance_To_workflowproj_SonataFlowProjInstance(a.(*SonataFlowProjInstance), b.(*workflowproj.SonataFlowProjInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*workflowproj.SonataFlowProjInstance)(nil), (*SonataFlowProjInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_workflowproj_SonataFlowProjInstance_To_v1alpha08_SonataFlowProjInstance(a.(*workflowproj.SonataFlowProjInstance), b.(*SonataFlowProjInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SonataFlowProjInstanceList)(nil), (*workflowproj.SonataFlowProjInstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha08_SonataFlowProjInstanceList_To_workflowproj_SonataFlowProjInstanceList(a.(*SonataFlowProjInstanceList), b.(*workflowproj.SonataFlowProjInstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*workflowproj.SonataFlowProjInstanceList)(nil), (*SonataFlowProjInstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_workflowproj_SonataFlowProjInstanceList_To_v1alpha08_SonataFlowProjInstanceList(a.(*workflowproj.SonataFlowProjInstanceList), b.(*SonataFlowProjInstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SonataFlowProjInstanceSpec)(nil), (*workflowproj.SonataFlowProjInstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha08_SonataFlowProjInstanceSpec_To_workflowproj_SonataFlowProjInstanceSpec(a.(*SonataFlowProjInstanceSpec), b.(*workflowproj.SonataFlowProjInstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*workflowproj.SonataFlowProjInstanceSpec)(nil), (*SonataFlowProjInstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_workflowproj_SonataFlowProjInstanceSpec_To_v1alpha08_SonataFlowProjInstanceSpec(a.(*workflowproj.SonataFlowProjInstanceSpec), b.(*SonataFlowProjInstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SonataFlowProjInstanceStatus)(nil), (*workflowproj.SonataFlowProjInstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha08_SonataFlowProjInstanceStatus_To_workflowproj_SonataFlowProjInstanceStatus(a.(*SonataFlowProjInstanceStatus), b.(*workflowproj.SonataFlowProjInstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*workflowproj.SonataFlowProjInstanceStatus)(nil), (*SonataFlowProjInstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_workflowproj_SonataFlowProjInstanceStatus_To_v1alpha08_SonataFlowProjInstanceStatus(a.(*workflowproj.SonataFlowProjInstanceStatus), b.(*SonataFlowProjInstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SonataFlowProjInstantiateRequestOptions)(nil), (*workflowproj.SonataFlowProjInstantiateRequestOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha08_SonataFlowProjInstantiateRequestOptions_To_workflowproj_SonataFlowProjInstantiateRequestOptions(a.(*SonataFlowProjInstantiateRequestOptions), b.(*workflowproj.SonataFlowProjInstantiateRequestOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*workflowproj.SonataFlowProjInstantiateRequestOptions)(nil), (*SonataFlowProjInstantiateRequestOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_workflowproj_SonataFlowProjInstantiateRequestOptions_To_v1alpha08_SonataFlowProjInstantiateRequestOptions(a.(*workflowproj.SonataFlowProjInstantiateRequestOptions), b.(*SonataFlowProjInstantiateRequestOptions), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha08_ProjObjectsRef_To_workflowproj_ProjObjectsRef(in *ProjObjectsRef, out *workflowproj.ProjObjectsRef, s conversion.Scope) error {
	out.Workflow = in.Workflow
	out.Properties = in.Properties
	out.Resources = *(*[]v1.LocalObjectReference)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_v1alpha08_ProjObjectsRef_To_workflowproj_ProjObjectsRef is an autogenerated conversion function.
func Convert_v1alpha08_ProjObjectsRef_To_workflowproj_ProjObjectsRef(in *ProjObjectsRef, out *workflowproj.ProjObjectsRef, s conversion.Scope) error {
	return autoConvert_v1alpha08_ProjObjectsRef_To_workflowproj_ProjObjectsRef(in, out, s)
}

func autoConvert_workflowproj_ProjObjectsRef_To_v1alpha08_ProjObjectsRef(in *workflowproj.ProjObjectsRef, out *ProjObjectsRef, s conversion.Scope) error {
	out.Workflow = in.Workflow
	out.Properties = in.Properties
	out.Resources = *(*[]v1.LocalObjectReference)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_workflowproj_ProjObjectsRef_To_v1alpha08_ProjObjectsRef is an autogenerated conversion function.
func Convert_workflowproj_ProjObjectsRef_To_v1alpha08_ProjObjectsRef(in *workflowproj.ProjObjectsRef, out *ProjObjectsRef, s conversion.Scope) error {
	return autoConvert_workflowproj_ProjObjectsRef_To_v1alpha08_ProjObjectsRef(in, out, s)
}

func autoConvert_v1alpha08_SonataFlowProjInstance_To_workflowproj_SonataFlowProjInstance(in *SonataFlowProjInstance, out *workflowproj.SonataFlowProjInstance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha08_SonataFlowProjInstanceSpec_To_workflowproj_SonataFlowProjInstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha08_SonataFlowProjInstanceStatus_To_workflowproj_SonataFlowProjInstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha08_SonataFlowProjInstance_To_workflowproj_SonataFlowProjInstance is an autogenerated conversion function.
func Convert_v1alpha08_SonataFlowProjInstance_To_workflowproj_SonataFlowProjInstance(in *SonataFlowProjInstance, out *workflowproj.SonataFlowProjInstance, s conversion.Scope) error {
	return autoConvert_v1alpha08_SonataFlowProjInstance_To_workflowproj_SonataFlowProjInstance(in, out, s)
}

func autoConvert_workflowproj_SonataFlowProjInstance_To_v1alpha08_SonataFlowProjInstance(in *workflowproj.SonataFlowProjInstance, out *SonataFlowProjInstance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_workflowproj_SonataFlowProjInstanceSpec_To_v1alpha08_SonataFlowProjInstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_workflowproj_SonataFlowProjInstanceStatus_To_v1alpha08_SonataFlowProjInstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_workflowproj_SonataFlowProjInstance_To_v1alpha08_SonataFlowProjInstance is an autogenerated conversion function.
func Convert_workflowproj_SonataFlowProjInstance_To_v1alpha08_SonataFlowProjInstance(in *workflowproj.SonataFlowProjInstance, out *SonataFlowProjInstance, s conversion.Scope) error {
	return autoConvert_workflowproj_SonataFlowProjInstance_To_v1alpha08_SonataFlowProjInstance(in, out, s)
}

func autoConvert_v1alpha08_SonataFlowProjInstanceList_To_workflowproj_SonataFlowProjInstanceList(in *SonataFlowProjInstanceList, out *workflowproj.SonataFlowProjInstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]workflowproj.SonataFlowProjInstance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha08_SonataFlowProjInstanceList_To_workflowproj_SonataFlowProjInstanceList is an autogenerated conversion function.
func Convert_v1alpha08_SonataFlowProjInstanceList_To_workflowproj_SonataFlowProjInstanceList(in *SonataFlowProjInstanceList, out *workflowproj.SonataFlowProjInstanceList, s conversion.Scope) error {
	return autoConvert_v1alpha08_SonataFlowProjInstanceList_To_workflowproj_SonataFlowProjInstanceList(in, out, s)
}

func autoConvert_workflowproj_SonataFlowProjInstanceList_To_v1alpha08_SonataFlowProjInstanceList(in *workflowproj.SonataFlowProjInstanceList, out *SonataFlowProjInstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]SonataFlowProjInstance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_workflowproj_SonataFlowProjInstanceList_To_v1alpha08_SonataFlowProjInstanceList is an autogenerated conversion function.
func Convert_workflowproj_SonataFlowProjInstanceList_To_v1alpha08_SonataFlowProjInstanceList(in *workflowproj.SonataFlowProjInstanceList, out *SonataFlowProjInstanceList, s conversion.Scope) error {
	return autoConvert_workflowproj_SonataFlowProjInstanceList_To_v1alpha08_SonataFlowProjInstanceList(in, out, s)
}

func autoConvert_v1alpha08_SonataFlowProjInstanceSpec_To_workflowproj_SonataFlowProjInstanceSpec(in *SonataFlowProjInstanceSpec, out *workflowproj.SonataFlowProjInstanceSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha08_SonataFlowProjInstanceSpec_To_workflowproj_SonataFlowProjInstanceSpec is an autogenerated conversion function.
func Convert_v1alpha08_SonataFlowProjInstanceSpec_To_workflowproj_SonataFlowProjInstanceSpec(in *SonataFlowProjInstanceSpec, out *workflowproj.SonataFlowProjInstanceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha08_SonataFlowProjInstanceSpec_To_workflowproj_SonataFlowProjInstanceSpec(in, out, s)
}

func autoConvert_workflowproj_SonataFlowProjInstanceSpec_To_v1alpha08_SonataFlowProjInstanceSpec(in *workflowproj.SonataFlowProjInstanceSpec, out *SonataFlowProjInstanceSpec, s conversion.Scope) error {
	return nil
}

// Convert_workflowproj_SonataFlowProjInstanceSpec_To_v1alpha08_SonataFlowProjInstanceSpec is an autogenerated conversion function.
func Convert_workflowproj_SonataFlowProjInstanceSpec_To_v1alpha08_SonataFlowProjInstanceSpec(in *workflowproj.SonataFlowProjInstanceSpec, out *SonataFlowProjInstanceSpec, s conversion.Scope) error {
	return autoConvert_workflowproj_SonataFlowProjInstanceSpec_To_v1alpha08_SonataFlowProjInstanceSpec(in, out, s)
}

func autoConvert_v1alpha08_SonataFlowProjInstanceStatus_To_workflowproj_SonataFlowProjInstanceStatus(in *SonataFlowProjInstanceStatus, out *workflowproj.SonataFlowProjInstanceStatus, s conversion.Scope) error {
	if err := Convert_v1alpha08_ProjObjectsRef_To_workflowproj_ProjObjectsRef(&in.ObjectsRef, &out.ObjectsRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha08_SonataFlowProjInstanceStatus_To_workflowproj_SonataFlowProjInstanceStatus is an autogenerated conversion function.
func Convert_v1alpha08_SonataFlowProjInstanceStatus_To_workflowproj_SonataFlowProjInstanceStatus(in *SonataFlowProjInstanceStatus, out *workflowproj.SonataFlowProjInstanceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha08_SonataFlowProjInstanceStatus_To_workflowproj_SonataFlowProjInstanceStatus(in, out, s)
}

func autoConvert_workflowproj_SonataFlowProjInstanceStatus_To_v1alpha08_SonataFlowProjInstanceStatus(in *workflowproj.SonataFlowProjInstanceStatus, out *SonataFlowProjInstanceStatus, s conversion.Scope) error {
	if err := Convert_workflowproj_ProjObjectsRef_To_v1alpha08_ProjObjectsRef(&in.ObjectsRef, &out.ObjectsRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_workflowproj_SonataFlowProjInstanceStatus_To_v1alpha08_SonataFlowProjInstanceStatus is an autogenerated conversion function.
func Convert_workflowproj_SonataFlowProjInstanceStatus_To_v1alpha08_SonataFlowProjInstanceStatus(in *workflowproj.SonataFlowProjInstanceStatus, out *SonataFlowProjInstanceStatus, s conversion.Scope) error {
	return autoConvert_workflowproj_SonataFlowProjInstanceStatus_To_v1alpha08_SonataFlowProjInstanceStatus(in, out, s)
}

func autoConvert_v1alpha08_SonataFlowProjInstantiateRequestOptions_To_workflowproj_SonataFlowProjInstantiateRequestOptions(in *SonataFlowProjInstantiateRequestOptions, out *workflowproj.SonataFlowProjInstantiateRequestOptions, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.MainWorkflowFile = in.MainWorkflowFile
	return nil
}

// Convert_v1alpha08_SonataFlowProjInstantiateRequestOptions_To_workflowproj_SonataFlowProjInstantiateRequestOptions is an autogenerated conversion function.
func Convert_v1alpha08_SonataFlowProjInstantiateRequestOptions_To_workflowproj_SonataFlowProjInstantiateRequestOptions(in *SonataFlowProjInstantiateRequestOptions, out *workflowproj.SonataFlowProjInstantiateRequestOptions, s conversion.Scope) error {
	return autoConvert_v1alpha08_SonataFlowProjInstantiateRequestOptions_To_workflowproj_SonataFlowProjInstantiateRequestOptions(in, out, s)
}

func autoConvert_workflowproj_SonataFlowProjInstantiateRequestOptions_To_v1alpha08_SonataFlowProjInstantiateRequestOptions(in *workflowproj.SonataFlowProjInstantiateRequestOptions, out *SonataFlowProjInstantiateRequestOptions, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.MainWorkflowFile = in.MainWorkflowFile
	return nil
}

// Convert_workflowproj_SonataFlowProjInstantiateRequestOptions_To_v1alpha08_SonataFlowProjInstantiateRequestOptions is an autogenerated conversion function.
func Convert_workflowproj_SonataFlowProjInstantiateRequestOptions_To_v1alpha08_SonataFlowProjInstantiateRequestOptions(in *workflowproj.SonataFlowProjInstantiateRequestOptions, out *SonataFlowProjInstantiateRequestOptions, s conversion.Scope) error {
	return autoConvert_workflowproj_SonataFlowProjInstantiateRequestOptions_To_v1alpha08_SonataFlowProjInstantiateRequestOptions(in, out, s)
}
