//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2023 Red Hat, Inc. and/or its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha08

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjObjectsRef) DeepCopyInto(out *ProjObjectsRef) {
	*out = *in
	out.Workflow = in.Workflow
	out.Properties = in.Properties
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjObjectsRef.
func (in *ProjObjectsRef) DeepCopy() *ProjObjectsRef {
	if in == nil {
		return nil
	}
	out := new(ProjObjectsRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonataFlowProjInstance) DeepCopyInto(out *SonataFlowProjInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonataFlowProjInstance.
func (in *SonataFlowProjInstance) DeepCopy() *SonataFlowProjInstance {
	if in == nil {
		return nil
	}
	out := new(SonataFlowProjInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SonataFlowProjInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonataFlowProjInstanceList) DeepCopyInto(out *SonataFlowProjInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SonataFlowProjInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonataFlowProjInstanceList.
func (in *SonataFlowProjInstanceList) DeepCopy() *SonataFlowProjInstanceList {
	if in == nil {
		return nil
	}
	out := new(SonataFlowProjInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SonataFlowProjInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonataFlowProjInstanceSpec) DeepCopyInto(out *SonataFlowProjInstanceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonataFlowProjInstanceSpec.
func (in *SonataFlowProjInstanceSpec) DeepCopy() *SonataFlowProjInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(SonataFlowProjInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonataFlowProjInstanceStatus) DeepCopyInto(out *SonataFlowProjInstanceStatus) {
	*out = *in
	in.ObjectsRef.DeepCopyInto(&out.ObjectsRef)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonataFlowProjInstanceStatus.
func (in *SonataFlowProjInstanceStatus) DeepCopy() *SonataFlowProjInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(SonataFlowProjInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonataFlowProjInstantiateRequestOptions) DeepCopyInto(out *SonataFlowProjInstantiateRequestOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonataFlowProjInstantiateRequestOptions.
func (in *SonataFlowProjInstantiateRequestOptions) DeepCopy() *SonataFlowProjInstantiateRequestOptions {
	if in == nil {
		return nil
	}
	out := new(SonataFlowProjInstantiateRequestOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SonataFlowProjInstantiateRequestOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
