apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: sonataflow-operator
  name: logic-operator-rhel8-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: sonataflow-operator
status:
  loadBalancer: {}
