name: E2E checks
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "LICENSE"
      - "**/.gitignore"
      - "**.md"
      - "**.adoc"
      - "*.txt"
      - "docsimg/**"
      - ".ci/jenkins/**"

env:
  GO_VERSION: 1.19

jobs:
  e2e:
    concurrency:
      group: kogito-serverless-operator-e2e-tests-${{ matrix.cluster-type }}-${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 120
    strategy:
      matrix:
        cluster-type:
        - kind
        - minikube
      fail-fast: false
    runs-on: ubuntu-latest
    name: End-to-end tests (${{ matrix.cluster-type }})
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Install Go
      id: go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: start minikube
      if: ${{ matrix.cluster-type == 'minikube' }}
      id: minikube
      uses: medyagh/setup-minikube@latest

    - name: Setup KIND cluster
      if: ${{ matrix.cluster-type == 'kind' }}
      uses: container-tools/kind-action@v1

    - name: Check pods
      run: |
        kubectl get pods -A
        sleep 10
        kubectl get pods -A
    
    ### TEST
    - name: Build img
      run: |
        make docker-build IMG=quay.io/kiegroup/kogito-serverless-operator:0.0.1
    - name: Load kind image
      if: ${{ matrix.cluster-type == 'kind' }}
      run: |
        kind load docker-image quay.io/kiegroup/kogito-serverless-operator:0.0.1
    - name: Load minikube image
      if: ${{ matrix.cluster-type == 'minikube' }}
      run: |
        minikube image load quay.io/kiegroup/kogito-serverless-operator:0.0.1
    - name: Run tests
      run: |
        kubectl get pods -A
        make install
        make deploy IMG=quay.io/kiegroup/kogito-serverless-operator:0.0.1
        sleep 10s
        kubectl get pods -A
        kubectl get deploy kogito-serverless-operator-controller-manager -o yaml -n kogito-serverless-operator-system
        sleep 10s
        kubectl get pods -A
        kubectl get deploy kogito-serverless-operator-controller-manager -o yaml -n kogito-serverless-operator-system
        sleep 10s
        kubectl get pods -A
        kubectl get deploy kogito-serverless-operator-controller-manager -o yaml -n kogito-serverless-operator-system
        sleep 10s
        kubectl get pods -A
        kubectl get deploy kogito-serverless-operator-controller-manager -o yaml -n kogito-serverless-operator-system
        make undeploy
    ### TEST

    - name: Run tests
      run: |
        make test-e2e
      env:
        CLUSTER_TYPE: ${{ matrix.cluster-type }}